CREATE DATABASE GELADEIRA;

CREATE TABLE Itens (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nome VARCHAR(100) NOT NULL,
    Andar INT NOT NULL,
    Container VARCHAR(100) NOT NULL,
    Posicao VARCHAR(100) NOT NULL
);